killbilling/recurly-java-library

src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Method to get invoice from subscription object for both nested and linked invoices.

update get account and get invoice methods on subscription object

---

src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Adds the functionality of [applying a coupon to an account when a subscription is created] (https://docs.recurly.com/api/subscriptions#create-subscription). Tests included.

adds the ability to apply coupon at subscription creation

---

pom.xml
src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Transaction.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

(enterprise feature). Tests included. https://docs.recurly.com/api/invoices#offline-manual-payment.

adds the ability to enter offline payments for manual invoices

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Adds method to RecurlyClient for getting a [single invoice](https://docs.recurly.com/api/invoices#get-invoice).

Adds method to get a single invoice

---

src/main/java/com/ning/billing/recurly/model/Accounts.java

Addresses issue discussed here:
https://github.com/killbilling/recurly-java-library/issues/98
Should have no functional change and pass all tests.

Fix root element for Accounts

---

.travis.yml

https://github.com/killbilling/recurly-java-library/issues/71
Have travis run the integration tests against a recurly sandbox account

Run integration tests on travis

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Addresses Issue https://github.com/killbilling/recurly-java-library/issues/105 reported by @shrihubble 
See the integration test for details

Implement updatePlan path in the RecurlyClient

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/util/http/SslUtils.java

Related to discussion in issue https://github.com/killbilling/recurly-java-library/issues/96
Set's the protocol to TLS version 1.2 or whatever is passed.

Enforce TLS 1.2

---

src/main/java/com/ning/billing/recurly/model/Adjustment.java
src/test/java/com/ning/billing/recurly/model/TestAdjustements.java

See https://dev.recurly.com/docs/create-a-charge-or-credit for more information on tax_exempt property for adjustments

Map tax_exempt xml field in Adjustment model class

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Coupon.java
src/main/java/com/ning/billing/recurly/model/Delivery.java
src/main/java/com/ning/billing/recurly/model/GiftCard.java
src/main/java/com/ning/billing/recurly/model/GiftCards.java
src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestDelivery.java
src/test/java/com/ning/billing/recurly/model/TestGiftCard.java

This adds support for gift cards. This is not currently documented or released on the API side. I will be adding some documentation and testing instructions here as they come in.

Gift Card Support

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Adds the route to preview a gift card purchase
@pierre do you think we can squeeze this into release?

Preview Gift Card

---

pom.xml
src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

-- Added support to retrieve invoice pdf as byte array
-- Added logic for sending and receiving response when content type is application/pdf

Add support to retrieve invoice pdf using invoice number

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Accounts.java
src/main/java/com/ning/billing/recurly/model/AddOns.java
src/main/java/com/ning/billing/recurly/model/Adjustments.java
src/main/java/com/ning/billing/recurly/model/Coupons.java
src/main/java/com/ning/billing/recurly/model/Invoices.java
src/main/java/com/ning/billing/recurly/model/Plans.java
src/main/java/com/ning/billing/recurly/model/RecurlyErrors.java
src/main/java/com/ning/billing/recurly/model/RecurlyObjects.java
src/main/java/com/ning/billing/recurly/model/Redemptions.java
src/main/java/com/ning/billing/recurly/model/SubscriptionAddOns.java
src/main/java/com/ning/billing/recurly/model/Subscriptions.java
src/main/java/com/ning/billing/recurly/model/Transactions.java

* adds abstract pagination methods - for generic usage
* allows http client overriding
* adds URI scheme argument in client constructor

Abstract pagination methods and http client overriding

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
src/main/java/com/ning/billing/recurly/model/ShippingAddress.java
src/main/java/com/ning/billing/recurly/model/ShippingAddresses.java
src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java

Support shipping addresses. Add multiple shipping addresses on an `Account` and assign shipping addresses to a `Subscription`.

Support for shipping addresses

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Adds the routes to get and delete adjustments given just their uuid.
Addresses issue #140

Add getAdjustment and deleteAdjustment

---

src/main/java/com/ning/billing/recurly/model/Invoice.java
src/test/java/com/ning/billing/recurly/model/TestInvoice.java

Adds closedAt to Invoice

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Throws a less vague exception for unauth calls

---

src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/model/TestSubscription.java

Fixes formatting of https://github.com/killbilling/recurly-java-library/pull/153

Fix formatting

---

src/main/java/com/ning/billing/recurly/QueryParams.java
src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/InvoiceState.java
src/main/java/com/ning/billing/recurly/model/Invoices.java
src/main/java/com/ning/billing/recurly/model/Subscription.java
src/main/java/com/ning/billing/recurly/model/SubscriptionState.java
src/main/java/com/ning/billing/recurly/model/Subscriptions.java
src/main/java/com/ning/billing/recurly/model/TransactionState.java
src/main/java/com/ning/billing/recurly/model/TransactionType.java
src/main/java/com/ning/billing/recurly/model/Transactions.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java

This PR enables using all the query params allowed in API version 2.4
See:
https://dev.recurly.com/docs/pagination
https://dev.recurly.com/docs/list-accounts
https://dev.recurly.com/docs/list-subscriptions
https://dev.recurly.com/docs/list-transactions

New API version 2.4 pagination params

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java

* Removes an unused import 
* Adds the site level `/subscriptions` endpoint

List site subscriptions

---

src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Add integration test for getSubscriptions()

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Address.java
src/main/java/com/ning/billing/recurly/model/BillingInfo.java
src/main/java/com/ning/billing/recurly/model/ShippingAddress.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java

Adding the GeoCode element. Still a work in progress.
This is going into the API version 2.5 branch.

Add geo code

---

src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/model/TestSubscription.java
src/test/java/com/ning/billing/recurly/model/TestSubscriptions.java

Multiple coupon codes on a Subscription

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java

Fix query param generation on getTransactions

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java

Replace uses of Guava's Objects#firstNonNull with MoreObjects#firstNonNull 

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Invoice.java
src/main/java/com/ning/billing/recurly/model/InvoiceRefund.java
src/main/java/com/ning/billing/recurly/model/RefundApplyOrder.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Resolves #169 
This PR is intended to support both open amount refunds on invoices. It's still a work in progress. I've decided to move the other refund method to a follow up PR.

Support open amount invoice refund

---

src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Remaining_billing_cycles unavailable in subscription element #178

PR for issue #178

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/main/java/com/ning/billing/recurly/model/Address.java
src/main/java/com/ning/billing/recurly/model/Adjustment.java
src/main/java/com/ning/billing/recurly/model/BillingInfo.java
src/main/java/com/ning/billing/recurly/model/Coupon.java
src/main/java/com/ning/billing/recurly/model/Invoice.java
src/main/java/com/ning/billing/recurly/model/Plan.java
src/main/java/com/ning/billing/recurly/model/ShippingAddress.java
src/main/java/com/ning/billing/recurly/model/Subscription.java
src/main/java/com/ning/billing/recurly/model/Transaction.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestAccount.java
src/test/java/com/ning/billing/recurly/model/TestAdjustment.java
src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java
src/test/java/com/ning/billing/recurly/model/TestCoupon.java
src/test/java/com/ning/billing/recurly/model/TestInvoices.java
src/test/java/com/ning/billing/recurly/model/TestSubscription.java
src/test/java/com/ning/billing/recurly/model/TestTransaction.java

These are all the changes needed to bump us to API version 2.5. Mostly some added fields and we added the `forceCollect` endpoint.

API version 2.5 changes

---

src/main/java/com/ning/billing/recurly/model/Transaction.java
src/test/java/com/ning/billing/recurly/model/TestTransaction.java

We decided we don't want these in the final API

Remove failureType and gatewayErrorCodes

---

src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/model/TestSubscription.java

This is going into the API version 2.6. Some more changes related to cardless free trials.

[V2.6] Cardless Free Trial changes

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/AbstractAddOn.java
src/main/java/com/ning/billing/recurly/model/AddOn.java
src/main/java/com/ning/billing/recurly/model/MeasuredUnit.java
src/main/java/com/ning/billing/recurly/model/MeasuredUnits.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestAddOns.java
src/test/java/com/ning/billing/recurly/model/TestMeasuredUnit.java
src/test/java/com/ning/billing/recurly/model/TestMeasuredUnits.java

1. Create usage based addons with measured units.
2. Create and list measured units.

Added support for measured units.

---

src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java

This fixes the integration tests. I think something may have changed around remainingBillingCycles but I cannot tell when. I am looking into the change on the server side. If this does appear to be a server side bug I will change the tests back.

Fix integration tests

---

src/main/java/com/ning/billing/recurly/model/push/payment/PushTransaction.java
src/test/java/com/ning/billing/recurly/model/push/TestNotification.java

Added failureType and gatewayErrorCodes to PushNotification (issue 190)

---

src/main/java/com/ning/billing/recurly/model/Adjustment.java
src/test/java/com/ning/billing/recurly/model/TestAdjustment.java

https://dev.recurly.com/docs/create-a-credit

Add revenue schedule type to adjustment

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/main/java/com/ning/billing/recurly/model/AccountAcquisition.java
src/main/java/com/ning/billing/recurly/model/AcquisitionChannel.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestAccountAcquisition.java

Addresses issue #206. You can see the `TestRecurlyClient#testAccountAcquisition` method to see usage.

Add account acquisition endpoint

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java

Resolves issue #211. Fixes that extra slash.

Resolves issue #211

---

src/main/java/com/ning/billing/recurly/model/BillingInfo.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java

Parse type attribute on BillingInfos

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Invoice.java
src/main/java/com/ning/billing/recurly/model/Purchase.java
src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestPurchase.java
src/test/java/com/ning/billing/recurly/model/TestSubscription.java

Only contains one change: https://github.com/killbilling/recurly-java-library/pull/216

API version 2.8 changes

---

src/main/java/com/ning/billing/recurly/model/TransactionError.java
src/test/java/com/ning/billing/recurly/model/TestTransaction.java

This is with respect to the issue #224.
We added the missing gateway_error_code into the Transaction error for mapping the error code to the custom processing.

Add the gateway_error_code to TransactionError. issue #224

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Addresses issue brought up in #227

Add updateAddOn method to Client

---

src/main/java/com/ning/billing/recurly/model/AbstractTransaction.java
src/main/java/com/ning/billing/recurly/model/push/payment/PushTransaction.java
src/test/java/com/ning/billing/recurly/model/TestTransaction.java

Refactored failureType out of PushTransaction and into AbstractTransaction since any type of transaction can have a failure type.

Refactored AbstractTransactions to include failure_type

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/AddOn.java
src/main/java/com/ning/billing/recurly/model/Adjustment.java
src/main/java/com/ning/billing/recurly/model/CreditPayment.java
src/main/java/com/ning/billing/recurly/model/CreditPayments.java
src/main/java/com/ning/billing/recurly/model/Invoice.java
src/main/java/com/ning/billing/recurly/model/InvoiceCollection.java
src/main/java/com/ning/billing/recurly/model/InvoiceRefund.java
src/main/java/com/ning/billing/recurly/model/Plan.java
src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
src/main/java/com/ning/billing/recurly/model/RefundMethod.java
src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/model/TestInvoices.java
src/test/java/com/ning/billing/recurly/model/TestRevenueScheduleType.java

This includes the changes needed for API version 2.10. There are a few breaking changes:
When creating or refunding invoices, we now return an InvoiceCollection object rather than an Invoice. If you wish to upgrade your application without changing functionality, we recommend that you use the `getChargeInvoice` method on the InvoiceCollection to get the charge Invoice. Example:
```java
// Change this:
final Invoice invoice = recurlyClient.postAccountInvoice(accountData.getAccountCode(), invoiceData);
// To this:
final InvoiceCollection collection = recurlyClient.postAccountInvoice(accountData.getAccountCode(), invoiceData);
final Invoice invoice = collection.getChargeInvoice();
```
If you want to preserve functionality, change any use of `Invoice#getSubtotalAfterDiscountInCents` to …

API version 2.10

---

src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
src/test/java/com/ning/billing/recurly/model/TestAccount.java

Fix for killbilling/recurly-java-library#214 issue

Add JsonProperty to fix jackson 2.9 issue

---

src/main/java/com/ning/billing/recurly/QueryParams.java
src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
src/main/java/com/ning/billing/recurly/model/Usages.java
src/test/java/com/ning/billing/recurly/model/TestUsages.java

As described here:
https://dev.recurly.com/docs/list-add-ons-usage

Support for "List Subscription Add-On's Usage"

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/main/java/com/ning/billing/recurly/model/Adjustment.java
src/main/java/com/ning/billing/recurly/model/Purchase.java
src/main/java/com/ning/billing/recurly/model/Subscription.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java

Here are the changes for API version 2.11. There are no breaking changes
* Account#preferredLocale Support
* Purchases multiple shipping addresses support
* Subscription pause and resume support

API v2.11 Changes

---

src/main/java/com/ning/billing/recurly/model/RecurlyUnitCurrency.java

Added indian rupees to RecurlyUnitCurrency

Add support INR (indian rupees)

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Resolves #251 
Adds missing endpoints for site-wide invoices
Resolves #253 
Adds missing Shipping Address endpoints

Add missing endpoints in RecurlyClient

---

src/main/java/com/ning/billing/recurly/model/CreditInvoices.java
src/main/java/com/ning/billing/recurly/model/InvoiceCollection.java
src/test/java/com/ning/billing/recurly/model/TestInvoiceCollection.java
src/test/java/com/ning/billing/recurly/model/TestPurchase.java

Resolves #259
InvoiceCollection was not appropriately parsing the credit_invoices array.

Fix the InvoiceCollection parser

---

src/main/java/com/ning/billing/recurly/model/Plan.java
src/main/java/com/ning/billing/recurly/model/Subscription.java

Subscription Terms feature for API version 2.13.

Susbcription Terms

---

README.md
pom.xml
src/main/java/com/ning/billing/recurly/RecurlyClient.java

API version 2.13

---

src/main/java/com/ning/billing/recurly/model/BillingInfo.java

Adds get/set for currency in billing info (allows users to specify the intended currency when setting billing info)

Add get/set currency to BillingInfo

---

src/main/java/com/ning/billing/recurly/model/Subscription.java
src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Allow updating subscription's shipping address

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/AbstractSubscription.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/main/java/com/ning/billing/recurly/model/CustomField.java
src/main/java/com/ning/billing/recurly/model/CustomFields.java
src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
src/main/java/com/ning/billing/recurly/model/Subscription.java
src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestAccount.java
src/test/java/com/ning/billing/recurly/model/TestCustomField.java
src/test/java/com/ning/billing/recurly/model/TestSubscription.java
src/test/java/com/ning/billing/recurly/model/TestSubscriptionUpdate.java

Add CustomField class in Account & Subscription

---

.gitignore
src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/model/TestCoupons.java

Remove unnecessary query param "per_page" from non-list endpoints

---

.gitignore
src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Address.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestInvoice.java

Allows for updating an invoice

Add ability to update an invoice

---

.gitignore
src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Address.java
src/main/java/com/ning/billing/recurly/model/SubscriptionNotes.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestInvoice.java

Changes for API 2.14. There are no breaking changes.

API version 2.14

---

.travis.yml
pom.xml
scripts/build
scripts/check-deps
scripts/install-deps
scripts/test
travis-test.sh

Added `scripts` folder for a standard interface to perform common tasks

Added `scripts` folder

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Add support for original_invoices

---

src/main/java/com/ning/billing/recurly/model/AbstractTransaction.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/main/java/com/ning/billing/recurly/model/Adjustment.java
src/main/java/com/ning/billing/recurly/model/Invoice.java
src/main/java/com/ning/billing/recurly/model/Transaction.java
src/main/java/com/ning/billing/recurly/model/push/payment/PushTransaction.java
src/test/java/com/ning/billing/recurly/model/TestAdjustment.java
src/test/java/com/ning/billing/recurly/model/TestTransaction.java

Fixes #242 
Playground script:
```java
import com.ning.billing.recurly.model.Invoices;
import com.ning.billing.recurly.model.Invoice;
import com.ning.billing.recurly.model.Adjustment;
import com.ning.billing.recurly.model.Transaction;
public class ListInvoices {
try {
client.open();
final Invoices invoices = client.getInvoices();
for (Invoice inv: invoices) {
for (Adjustment adj: inv.getLineItems()) {
System.out.println("Refundable Total: " + adj.getRefundableTotalInCents());
System.out.println("State: " + adj.getState());
System.out.println("Proration Rate: " + adj.getProrationRate());
}
for (Transaction trans: inv.getTransactions()) {
System.out.println("IP …
```

Add missing properties relevant to listing all invoices

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java

Bumped to API version 2.16. There are no breaking changes.

API Version 2.16

---

src/main/java/com/ning/billing/recurly/model/push/Notification.java
src/main/java/com/ning/billing/recurly/model/push/subscription/PushSubscription.java
src/main/java/com/ning/billing/recurly/model/push/subscription/SubscriptionPausedNotification.java
src/main/java/com/ning/billing/recurly/model/push/subscription/SubscriptionResumedNotification.java
src/test/java/com/ning/billing/recurly/model/push/TestNotification.java

Fixes #307 and #309 
There was a couple of mismatches between the docs (true behavior) and the way the library was written to handle these webhooks. This PR fixes those issues.

Fix webhooks

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/test/java/com/ning/billing/recurly/model/TestAccount.java

This brings us up to API version 2.19.
* Adds support for Account Hierarchy [PR](https://github.com/killbilling/recurly-java-library/pull/315)

Release API version 2.19

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Purchase.java
src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
src/main/java/com/ning/billing/recurly/model/ShippingFee.java
src/main/java/com/ning/billing/recurly/model/ShippingFees.java
src/main/java/com/ning/billing/recurly/model/ShippingMethod.java
src/main/java/com/ning/billing/recurly/model/ShippingMethods.java
src/main/java/com/ning/billing/recurly/model/Subscription.java

This adds support for shipping fees and the new shipping methods endpoint.
List shipping methods:
```java
ShippingMethods methods = client.getShippingMethods();
System.out.println(methods);
```
Get a shipping method:
```java
// Assumes a shipping method with code 'fast_fast_fast' exists on site
final ShippingMethod shippingMethod = client.getShippingMethod("fast_fast_fast");
System.out.println("Shipping Method found: " + shippingMethod.getName());
```
Purchase with shipping fees (note: either account must have shipping address, or purchase must have shipping_address_id):
```java
// Assumes Plan "gold" exists on the site
// Assumes shipping method "fast_fast_fast" exists on the site
final Account accountData = new Account();
accountData.setAccountCode("x");
final BillingInfo …
```

Add support for shipping fees

---

src/main/java/com/ning/billing/recurly/model/Purchase.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestPurchase.java

- Add shipping address to Purchase class
- Add shipping address tests to TestPurchase 
- Add shipping address to Purchase builder

Add shipping address to purchase

---

pom.xml
src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

- Update `generateUniqueCodes()` to return array of coupons (e.g. return object `coupons`: `coupons.get(0).getCouponCode()` yields `whatevercode123`
- Alter `callRecurlyXmlContent()` to return coupons when `clazz == Coupons.class`
```java
Coupon genCouponData = new Coupon();
genCouponData.setNumberOfUniqueCodes(3);
Coupons coupons = recurlyClient.generateUniqueCodes(coupon.getCouponCode(), genCouponData);
Coupon c = coupons.get(0);
System.out.println("Coupon c " + c.toString());
```

Update generateUniqueCodes to return coupons

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Adjustment.java
src/main/java/com/ning/billing/recurly/model/Item.java
src/main/java/com/ning/billing/recurly/model/Items.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestItem.java

Add Item class to Java Client Library
To create an item:
```java
final Item item = new Item();
item.setItemCode("iron_maidens");
item.setName("Iron Maidens");
client.createItem(item);
```
To look up an item (item_code required):
```java
final Item item = client.getItem("iron_maiden");
```
To update an item (item_code required):
```java
final Item item = new Item();
item.setItemCode("powder_puff");
item.setName("Powder Puff");
client.createItem(item);
final CustomFields customFields = new CustomFields();
final CustomField field = new CustomField();
field.setName("size");
field.setValue("small");
customFields.add(field);
item.setCustomFields(customFields);
final Item updatedItem = client.updateItem(item);
```
To delete an item (item_code required):
```java
client.deleteItem("powder_puff"); …
```

Add Item class 

---

src/main/java/com/ning/billing/recurly/model/push/Notification.java
src/main/java/com/ning/billing/recurly/model/push/item/DeactivatedItemNotification.java
src/main/java/com/ning/billing/recurly/model/push/item/ItemNotification.java
src/main/java/com/ning/billing/recurly/model/push/item/NewItemNotification.java
src/main/java/com/ning/billing/recurly/model/push/item/ReactivatedItemNotification.java
src/main/java/com/ning/billing/recurly/model/push/item/UpdatedItemNotification.java
src/test/java/com/ning/billing/recurly/model/push/TestNotification.java

Includes
`NewItemNotification`
`UpdatedItemNotification`
`DeactivatedItemNotification`
`ReactivatedItemNotification`

Add Item push notifications

---

src/main/java/com/ning/billing/recurly/model/CreditPayment.java
src/main/java/com/ning/billing/recurly/model/Invoice.java
src/test/java/com/ning/billing/recurly/model/TestInvoice.java

In response to https://github.com/killbilling/recurly-java-library/issues/361
- Add `credit_payment` to `Invoice`
- Add `applied_to_invoice` to `CreditPayment`

Add credit_payments to Invoice

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Transaction.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

Addresses https://github.com/killbilling/recurly-java-library/issues/330
- Add `getTransactionSubscriptions` to Recurly Client
- Remove `Transaction#Subscriptions`
- Include `getTransactionSubscriptions` in `TestRecurlyClient`

Add `getTransactionSubscriptions` to Recurly Client

---

src/main/java/com/ning/billing/recurly/model/Adjustment.java

Updates Adjustment to return `external_sku` if the merchant is using the Item Catalog.
See https://github.com/killbilling/recurly-java-library/pull/368 for more information about Items.

Add `externalSku` to Adjustment class

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java

To convert trial to paid subscription with 3ds token:
```java
client.convertTrial(subscription.getUuid(), token)
```
To convert trial for non-3ds where subscription has billing info:
```java
client.convertTrial(subscription.getUuid())
```
To convert trial to paid subscription with transaction type:
```java
client.convertTrialMoto(subscription.getUuid())
```

Add convertTrial() to Subscription

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/BillingInfo.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java

Now that Recurly API v2.26 is live, the feature(s) below can be merged into master
- Add IBAN attribute to BillingInfo https://github.com/killbilling/recurly-java-library/pull/384

Merge v2.26 features into master branch for release 

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/AddOn.java
src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
src/main/java/com/ning/billing/recurly/model/Tier.java
src/main/java/com/ning/billing/recurly/model/Tiers.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestAddOnsTiered.java

To create an add-on with tiered pricing:
```java
final Plan plan = Main.CreatePlan(client);
final AddOn ao = new AddOn();
ao.setAddOnCode("add_on_code");
ao.setName("Tiered Add-On");
ao.setTierType("tiered");
final RecurlyUnitCurrency price = new RecurlyUnitCurrency();
final Tiers tiers = new Tiers();
final Tier tierData = new Tier();
price.setUnitAmountUSD(100);
tierData.setUnitAmountInCents(price);
tierData.setEndingQuantity(20);
tiers.add(tierData);
final Tier tierData2 = new Tier();
price.setUnitAmountUSD(80);
tierData2.setUnitAmountInCents(price);
tiers.add(tierData2);
ao.setTiers(tiers);
final AddOn addon = client.createPlanAddOn(plan.getPlanCode(), ao);
```

Tiered pricing

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Coupon.java

Implements https://dev.recurly.com/docs/restore-coupon

Implements restore coupon

---

src/main/java/com/ning/billing/recurly/model/ResponseMetadata.java

Fix getStatusCode infinite loop

---

README.md
src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/BillingInfo.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java

- Bump to API version 2.28.
- BECS support https://github.com/killbilling/recurly-java-library/pull/407

Bump to API v2.28

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java

- Bump to API version 2.29
- Add tax identifier fields to billing info https://github.com/killbilling/recurly-java-library/pull/413

Bump to API v2.29

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClientUserAgent.java

See https://github.com/killbilling/recurly-java-library/pull/402

Fix conflicts from https://github.com/killbilling/recurly-java-library/pull/402

---

.github/workflows/ci.yml
.travis.yml
pom.xml

.github: switch to GitHub Actions

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/test/java/com/ning/billing/recurly/TestRecurlyClient.java

- Also updated links to documentation
- Added tests for capture and cancel purchase
Addresses https://github.com/killbilling/recurly-java-library/issues/419

Add cancel and capture purchase functionality

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/main/java/com/ning/billing/recurly/model/BillingInfo.java
src/main/java/com/ning/billing/recurly/model/BillingInfos.java
src/main/java/com/ning/billing/recurly/model/Invoice.java
src/main/java/com/ning/billing/recurly/model/Purchase.java
src/main/java/com/ning/billing/recurly/model/Subscription.java
src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java
src/test/java/com/ning/billing/recurly/model/TestInvoice.java
src/test/java/com/ning/billing/recurly/model/TestPurchase.java
src/test/java/com/ning/billing/recurly/model/TestSubscription.java
src/test/java/com/ning/billing/recurly/model/TestSubscriptionUpdate.java

POST v2/accounts/:account_code/billing_infos
```java
final Account account = client.getAccount("accountCode");
billingInfo.setAccountNumber("123456789123");
billingInfo.setAccountType("savings");
billingInfo.setRoutingNumber("123456780");
billingInfo.setNameOnAccount("Java Time");
billingInfo.setAddress1("1234567 Paper Street");
billingInfo.setCity("Los Angeles");
billingInfo.setState("CA");
billingInfo.setZip("95312");
billingInfo.setCountry("US");
client.createBillingInfo(account.getAccountCode(), billingInfo);
```
GET v2/accounts/{account_code}/billing_infos
```java
final BillingInfos binfos = client.getBillingInfos(account.getAccountCode());
```
GET v2/accounts/{account_code}/billing_infos/{uuid}
```java
final BillingInfo binfo = …
```

Wallet and Backup Payment

---

src/main/java/com/ning/billing/recurly/model/Invoice.java
src/main/java/com/ning/billing/recurly/model/TaxDetail.java
src/test/java/com/ning/billing/recurly/model/TestInvoice.java

Update `TaxDetail` class and associate list of `TaxDetail`s to `Invoice` class.

Tax details update

---

src/main/java/com/ning/billing/recurly/model/BillingInfo.java
src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java

Add `ideal` and `sofort` as billing_info's `online_banking_payment_type`.

Add onlineBankingPaymentType to BillingInfo

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/main/java/com/ning/billing/recurly/model/InvoiceTemplate.java
src/main/java/com/ning/billing/recurly/model/InvoiceTemplates.java
src/test/java/com/ning/billing/recurly/model/TestInvoiceTemplates.java

* Add `InvoiceTemplate` model
```
final InvoiceTemplate it = client.getInvoiceTemplate("q0tzf7o7fpbl");
final InvoiceTemplates its = client.getInvoiceTemplates();
```
* Add  setter and getter for `invoice_template_uuid ` and `getInvoiceTemplate` method to `Account`
```
Account account = new Account();
account.setInvoiceTemplateUuid("q0tzf7o7fpbl");
account = client.updateAccount(account.getAccountCode(), account1);
account.getInvoiceTemplate().getCode();
```

V2: Add suport for invoice templates

---

pom.xml
src/main/java/com/ning/billing/recurly/model/AbstractAddOn.java
src/main/java/com/ning/billing/recurly/model/AddOn.java
src/main/java/com/ning/billing/recurly/model/AddonPercentageTier.java
src/main/java/com/ning/billing/recurly/model/AddonPercentageTiers.java
src/main/java/com/ning/billing/recurly/model/CurrencyPercentageTier.java
src/main/java/com/ning/billing/recurly/model/CurrencyPercentageTiers.java
src/main/java/com/ning/billing/recurly/model/PercentageTier.java
src/main/java/com/ning/billing/recurly/model/PercentageTiers.java
src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
src/main/java/com/ning/billing/recurly/model/SubscriptionAddOn.java
src/main/java/com/ning/billing/recurly/model/UsageTimeframeType.java
src/test/java/com/ning/billing/recurly/TestUtils.java
src/test/java/com/ning/billing/recurly/model/TestAddOns.java
src/test/java/com/ning/billing/recurly/model/TestAddOnsPercentageTiered.java
src/test/java/com/ning/billing/recurly/model/TestSubscriptionAddOnWithPercentageTiers.java

Description:
Add support to create addon and subscription addon with percentage tiers.
Add support to usage_timeframe on plan addon and subscription addon.
Add tests for usage_timeframe, percentage tiered addon and percentage tiered subscription addon.
Add method on test utils to create a subscription addon and a plan addon with percentage tiers.

[API V2] Client Library and Doc Update - Java

---

src/main/java/com/ning/billing/recurly/model/Adjustment.java
src/main/java/com/ning/billing/recurly/model/AdjustmentRefund.java
src/main/java/com/ning/billing/recurly/model/Usage.java
src/test/java/com/ning/billing/recurly/model/TestAdjustment.java
src/test/java/com/ning/billing/recurly/model/TestUsage.java

Add `quantity_decimal` and `quantity_decimal_remaining` fields to `Adjustment` class.  Also add missing `quantity_remaining` field to `Adjustment` class.  Add `amount_decimal` field to `Usage` class.

Add fields for decimal usage

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/Account.java
src/main/java/com/ning/billing/recurly/model/CustomerPermission.java
src/main/java/com/ning/billing/recurly/model/Entitlement.java
src/main/java/com/ning/billing/recurly/model/Entitlements.java
src/test/java/com/ning/billing/recurly/model/TestAccountEntitlements.java

- Add `CustomerPermission`, `Entitlements` and `Entitlement` models.
- Add `GET v2/accounts/{account_code}/entitlements` to the client.

[API v2] Client library update, add entitlements

---

src/main/java/com/ning/billing/recurly/model/AbstractAddOn.java
src/main/java/com/ning/billing/recurly/model/AddOn.java
src/main/java/com/ning/billing/recurly/model/SubscriptionAddOn.java
src/main/java/com/ning/billing/recurly/model/UsageCalculationType.java
src/test/java/com/ning/billing/recurly/model/TestAddOns.java

Add `usage_calculation_type` to add-ons.

Add usage_calculation_type to add-ons

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/ExternalCharge.java
src/main/java/com/ning/billing/recurly/model/ExternalInvoice.java
src/main/java/com/ning/billing/recurly/model/ExternalInvoices.java
src/main/java/com/ning/billing/recurly/model/LineItems.java
src/test/java/com/ning/billing/recurly/model/TestExternalInvoice.java
src/test/java/com/ning/billing/recurly/model/TestExternalInvoices.java

Description:
GET v2/external_invoices
GET v2/external_invoices/{id}
GET v2/accounts/{account_id}/external_invoices
GET v2/external_subscriptions/{external_subscription_id}/external_invoices

External Invoices: Java Client Libraries & Docs

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/ExternalAccount.java
src/main/java/com/ning/billing/recurly/model/ExternalAccounts.java
src/test/java/com/ning/billing/recurly/model/TestExternalAccount.java
src/test/java/com/ning/billing/recurly/model/TestExternalAccounts.java

GET /sites/{site_id}/accounts/{account_id}/external_accounts
GET /sites/{site_id}/accounts/{account_id}/external_accounts/{external_account_uuid}
POST /sites/{site_id}/accounts/{account_id}/external_accounts
PUT /sites/{site_id}/accounts/{account_id}/external_accounts/{external_account_uuid}
DELETE /sites/{site_id}/accounts/{account_id}/external_accounts/{external_account_uuid}

External Accounts: Java Client Libraries & Docs

---

src/test/java/com/ning/billing/recurly/model/TestInvoice.java

Fixes failing test introduced in https://github.com/killbilling/recurly-java-library/pull/463 and https://github.com/killbilling/recurly-java-library/pull/464

Fix issues with failing test related to usedTaxService

---

src/main/java/com/ning/billing/recurly/model/BillingInfo.java
src/main/java/com/ning/billing/recurly/model/GatewayAttributes.java
src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java

Adds gateway_attributes field to BillingInfo.
gateway_attributes takes an account_reference

Add gateway_attributes and account_reference to BillingInfo

---

src/main/java/com/ning/billing/recurly/model/SubscriptionRampInterval.java
src/test/java/com/ning/billing/recurly/model/TestSubscription.java

Adds `starting_on` and `ending_on` to `SubscriptionRampInterval`

[API v2] Add starting_on and ending_on to SubscriptionRampInterval

---

src/main/java/com/ning/billing/recurly/model/ProrationSettings.java
src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
src/test/java/com/ning/billing/recurly/model/TestSubscriptionUpdate.java

Adds proration support for subscription update in from of ProrationSettings object, along with specs.

Add proration support to subscription update

---

src/main/java/com/ning/billing/recurly/RecurlyClient.java
src/main/java/com/ning/billing/recurly/model/ExternalSubscription.java
src/test/java/com/ning/billing/recurly/model/TestExternalSubscription.java
src/test/java/com/ning/billing/recurly/model/TestExternalSubscriptions.java

Added new method to get external_subscription by external_id.

GET external_subscription by external_id

---

src/main/java/com/ning/billing/recurly/model/Plan.java
src/test/java/com/ning/billing/recurly/model/TestPlan.java

adds support for vertex_transaction_type on plan

adds support for plan vertex_transaction_type
