- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionNotes.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
Adds the ability to define subscription notes (for purposes of customer communication) for a new subscription. Also allows you to [update an existing subscription's notes](https://docs.recurly.com/api/subscriptions#update-subscription-notes).
> adds sub notes

- README.md
- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClientUserAgent.java
Recurly API requests should be made to ":subdomain.recurly.com" rather than "api.recurly.com". This allows for easier troubleshooting.
> Replaces "api.recurly.com" w/ ":subdomain.recurly.com" for easier troubleshooting.

- src/main/java/com/ning/billing/recurly/model/push/Notification.java
- src/main/java/com/ning/billing/recurly/model/push/payment/VoidPaymentNotification.java
- src/test/java/com/ning/billing/recurly/model/push/TestNotification.java
- src/test/java/com/ning/billing/recurly/model/push/TestVoidNotification.java
Refactored voidedNotification to voidNotification to fit recurlys object.  Also fixed ability to parse the void_payment_notification webhook.
This PR address:
https://github.com/killbilling/recurly-java-library/issues/75
> Void Notification Parsing Issues

- README.md
- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/RecurlyJs.java
- src/test/java/com/ning/billing/recurly/model/TestAccount.java
- src/test/java/com/ning/billing/recurly/model/TestAccounts.java
- src/test/java/com/ning/billing/recurly/model/TestAddOns.java
- src/test/java/com/ning/billing/recurly/model/TestAdjustements.java
- src/test/java/com/ning/billing/recurly/model/TestAdjustment.java
- src/test/java/com/ning/billing/recurly/model/TestCoupon.java
- src/test/java/com/ning/billing/recurly/model/TestCoupons.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
- src/test/java/com/ning/billing/recurly/model/TestInvoices.java
- src/test/java/com/ning/billing/recurly/model/TestPlan.java
- src/test/java/com/ning/billing/recurly/model/TestPlans.java
- src/test/java/com/ning/billing/recurly/model/TestRedemption.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
- src/test/java/com/ning/billing/recurly/model/TestSubscriptionUpdate.java
- src/test/java/com/ning/billing/recurly/model/TestSubscriptions.java
- src/test/java/com/ning/billing/recurly/model/push/TestNotification.java
- src/test/java/com/ning/billing/recurly/model/push/TestVoidNotification.java
Recurly recently switched from `docs.recurly.com/api` to `dev.recurly.com` a. Navigating to an old docs link will redirect to the new docs site. These changes just make that new URL explicit.
> Updating docs links

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/RecurlyJs.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
Seemingly attempting to `mvn install` under jdk8 fails to build the documentation with lots of errors like this:
recurly-java-library/src/main/java/com/ning/billing/recurly/RecurlyJs.java:74: error: self-closing element not allowed
[ERROR] * <p/>
This patch fixes these errors.
> Remove self-closing elements, eliminating jdk 1.8 javadoc complaints

- src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
Upgrading to Jackson 2.5 or higher causes recurly api calls to stop working. An example of a failed create subscription call:
```
<?xml version="1.0" encoding="UTF-8"?>
<error>
<symbol>invalid_xml</symbol>
<description>The provided XML was invalid.</description>
<details>Unacceptable tag &lt;state&gt;</details>
</error>
```
This is the actual xml generated by recurly java library:
```
<subscription><unit_amount_in_cents/><quantity/><plan_code>full</plan_code><account><address/><account_code>xxxxxxxxxx</account_code><state/><username/><email/><first_name/><last_name/><company_name/><accept_language/><hosted_login_token/><created_at/><billing_info><account/><first_name/><last_name/><company/><address1/><address2/><city/><state/><zip/><country/><phone/><vat_number/><ip_address/><ip_address_co …
```
> using Jackson 2.5 and up causes issues when interacting with reculry

- src/main/java/com/ning/billing/recurly/model/AbstractTransaction.java
- src/main/java/com/ning/billing/recurly/model/Transaction.java
- src/main/java/com/ning/billing/recurly/model/push/payment/PushTransaction.java
- src/test/java/com/ning/billing/recurly/model/TestTransaction.java
- src/test/java/com/ning/billing/recurly/model/push/TestNotification.java
This is for Issue https://github.com/killbilling/recurly-java-library/issues/79
A few of the Transaction fields are mapped incorrectly or are missing.
1.  cvv_result, avs_result were both being mapped to the PushTransaction, but needs to also appear in the regular Transaction object.  Both share the AbstractTransaction object, so I put the mapping in there.
2.  avs_result_street and avs_result_postal are missing from the mappings.  Since these are shared by both the PushTransaction and regular Transaction object, I put it inside the AbstractTransaction object.
3.  'source' field was being mapped to the Transaction object, but appears in a few webhooks.  B/c it is shared by PushTransaction also, I put this field inside AbstractTransaction.
> Issue 79 - Fixed Transaction Mappings

- src/main/java/com/ning/billing/recurly/model/push/Notification.java
- src/main/java/com/ning/billing/recurly/model/push/invoice/ClosedInvoiceNotification.java
- src/main/java/com/ning/billing/recurly/model/push/invoice/InvoiceNotification.java
- src/main/java/com/ning/billing/recurly/model/push/invoice/NewInvoiceNotification.java
- src/main/java/com/ning/billing/recurly/model/push/invoice/PastDueInvoiceNotification.java
- src/main/java/com/ning/billing/recurly/model/push/invoice/ProcessingInvoiceNotification.java
- src/main/java/com/ning/billing/recurly/model/push/invoice/PushInvoice.java
- src/test/java/com/ning/billing/recurly/model/push/TestNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestCloseInvoiceNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestNewInvoiceNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestPastDueInvoiceNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestProcessingInvoiceNotification.java
As per the docs (https://docs.recurly.com/api/push-notifications), there are invoice webhooks:  "Recurly will send you the proper invoice notifications when your application creates or updates an invoice state." 
This pull request adds those mappings in as well as adding tests for both the invoice section of the xml, as well as tests for each type of complete invoice webhook.
> Added invoice webhooks

- src/test/java/com/ning/billing/recurly/TestUtils.java
Fixes the billing info expiration year for the integration tests:
https://github.com/killbilling/recurly-java-library/blob/master/src/test/java/com/ning/billing/recurly/TestUtils.java#L99_L101
Changing to 2020 to give us some room.
> Fix test billing info expiration year

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Redemption.java
- src/main/java/com/ning/billing/recurly/model/Redemptions.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestRedemptions.java
This PR is in reference to issue https://github.com/killbilling/recurly-java-library/issues/97
It's still a work in progress but I wanted to open it up to comments.
A few comments:
* Since we are now using Recurly API v2.1 we may want to use a major version bump when deploying.
* For the integration tests to run you'll need to set support for multiple coupon redemptions on your `Coupon > Settings` page 
\cc @pierre @cbsi-sl
> Support multiple coupon redemptions

- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
The invoice object was missing the original invoice link, this object is populated when you have a refund invoice and the original invoice indicates the invoice for which the refund was applied. This is to fix issue #106
> Added originial invoice to the invoice object.

- README.md
- src/main/java/com/ning/billing/recurly/util/http/SslUtils.java
This updates the README to explain how to use the `tlsProtocol` property.
I also needed to fix the spelling on those *_PROTOCOL_* constants.
@pierre What do you think of adding another section in the readme that states we only support Java 7 and above?
> Add TLS property documentation

- src/main/java/com/ning/billing/recurly/model/Coupon.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
This feature is in production but is not available for every site yet. I've added the feature to our sandbox site. It's supposed to be available on Thursday.
The feature is a special type of coupon that allows an extension of your subscription trial period.
The API changes are only a few added fields.
\cc @pierre
> Support for trial extension coupons

- src/main/java/com/ning/billing/recurly/model/Coupon.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
@pierre Sorry to expose you to this.
The team responsible for this feature decided to change the name of the feature and thus these API fields. They changed it from trial extension to free trial. This should not affect anyone as the feature is not being used by anyone yet. I have been assured this is the final API. Sorry again.
> Change name of free trial api attributes

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/RecurlyAPIError.java
Meant to address https://github.com/killbilling/recurly-java-library/issues/116
\cc @steelThread
You should be able to get the response code:
```java
apiException.getRecurlyError().getHttpStatusCode();
```
> Add HTTP status to exception

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Account.java
- src/main/java/com/ning/billing/recurly/model/AddOn.java
- src/main/java/com/ning/billing/recurly/model/Adjustment.java
- src/main/java/com/ning/billing/recurly/model/Coupon.java
- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/main/java/com/ning/billing/recurly/model/Plan.java
- src/main/java/com/ning/billing/recurly/model/Redemption.java
- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/main/java/com/ning/billing/recurly/model/Transaction.java
- src/test/java/com/ning/billing/recurly/model/TestAccount.java
- src/test/java/com/ning/billing/recurly/model/TestAddOns.java
- src/test/java/com/ning/billing/recurly/model/TestAdjustements.java
- src/test/java/com/ning/billing/recurly/model/TestCoupon.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
- src/test/java/com/ning/billing/recurly/model/TestPlan.java
- src/test/java/com/ning/billing/recurly/model/TestRedemptions.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
- src/test/java/com/ning/billing/recurly/model/TestTransaction.java
This updates the HTTP API to version 2.2.
This brings the `updated_at` field and some other features which I can add in a piecemeal fashion later. This should be the minimum required to get some new features into this library.
> Update to API version 2.2

- src/main/java/com/ning/billing/recurly/PaginationUtils.java
- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/AccountBalance.java
- src/main/java/com/ning/billing/recurly/model/Accounts.java
- src/main/java/com/ning/billing/recurly/model/AddOn.java
- src/main/java/com/ning/billing/recurly/model/AddOns.java
- src/main/java/com/ning/billing/recurly/model/Adjustments.java
- src/main/java/com/ning/billing/recurly/model/Coupons.java
- src/main/java/com/ning/billing/recurly/model/Invoices.java
- src/main/java/com/ning/billing/recurly/model/Plan.java
- src/main/java/com/ning/billing/recurly/model/Plans.java
- src/main/java/com/ning/billing/recurly/model/RecurlyErrors.java
- src/main/java/com/ning/billing/recurly/model/RecurlyObjects.java
- src/main/java/com/ning/billing/recurly/model/Redemptions.java
- src/main/java/com/ning/billing/recurly/model/RevenueScheduleType.java
- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionAddOns.java
- src/main/java/com/ning/billing/recurly/model/Subscriptions.java
- src/main/java/com/ning/billing/recurly/model/Transactions.java
- src/test/java/com/ning/billing/recurly/TestPaginationUtils.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/model/TestAccountBalance.java
- src/test/java/com/ning/billing/recurly/model/TestAddOns.java
- src/test/java/com/ning/billing/recurly/model/TestPlan.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
This updates us to API version 2.3.
The biggest change here is the deprecation of going backwards in pagination. We have also added support for getting the account balance which was the last feature advantage that v1 had over v2.
* Add revenue recognition fields
* Remove support for `prev` in pagination
* Add `AccountBalance`
> Update to API version 2.3

- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
- src/test/java/com/ning/billing/recurly/model/TestInvoices.java
- src/test/java/com/ning/billing/recurly/model/push/TestNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestCloseInvoiceNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestNewInvoiceNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestPastDueInvoiceNotification.java
-- Change "po_number" in Invoice class from Integer to String. "po_number" must be a String per https://dev.recurly.com/docs/post-an-invoice-invoice-pending-charges-on-an-acco
-- Update tests for deserialization
> Fix po number

- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
* Was using a static coupon code value, if the tests failed to clean
this up then all tests would fail after. Changed it to be random.
* Removed calls to clear billing info. Closing the account suffices.
> Fixes inconsistent integration tests

- src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
- src/main/java/com/ning/billing/recurly/model/jackson/RecurlyObjectsSerializer.java
Using Jackson 2.6.X or 2.7.X, I ran into serialization issue when sending a SubscriptionUpdate with multiple SubcriptionAddOn elements. I narrowed this down to an issue between Jackson 2.5 and 2.6+. If you update jackson version to 2.6+ in recurly-java-library, the following unit test fails:
`testDeserializationWithAddons(com.ning.billing.recurly.model.TestSubscription): Can not start an object, expecting field name`
The use of JsonInclude.NON_EMPTY also causes problems in Jackson 2.6, namely that Integer fields with value 0 are treated as null. This caused TestAdjustment unit test to fail with error:
```
java.lang.NullPointerException
at com.ning.billing.recurly.model.TestAdjustment.testSerialization(TestAdjustment.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) …
```
> Jackson 2.6 serialization fix

- src/main/java/com/ning/billing/recurly/model/RecurlyUnitCurrency.java
Now Recurly supports JPY (Japanese currency).
> Add JPY to list of supported currencies 

- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
These tests fail sometimes if the times are slightly off. Since the intention is to test that the datetimes are properly serialized and parseable, I've removed them. This is already tested in the unit tests.
> Stabilize integration tests

- .travis.yml
- pom.xml
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- travis-test.sh
Have travis only run unit tests if the `API_KEY` is not set. `API_KEY` is not set when running tests on public PRs. I have to run the integration tests for every PR anyway.
> Run unit tests only for public PRs

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
Addresses issue https://github.com/killbilling/recurly-java-library/issues/147
Do we want to keep the old method and deprecate it? Should we have both methods supported and just add some more documentation into the methods?
> Support invoices with prefix

- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
Resolves: https://github.com/killbilling/recurly-java-library/issues/152
Added a null check for the String revenueScheduleType.
You may want to consider updating the enum RevenueScheduleType to return a default value if the string is empty
> Added null check for revenueScheduleType

- README.md
The travis badge was just showing the latest build (which would include
failing experiemental branches). We want it to only show master which is
green and makes people feel good when they see the README :)
> Make travis badge reflect master branch only

- src/main/java/com/ning/billing/recurly/model/Adjustment.java
- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/main/java/com/ning/billing/recurly/model/JurisDetail.java
- src/main/java/com/ning/billing/recurly/model/JurisDetails.java
- src/main/java/com/ning/billing/recurly/model/TaxType.java
- src/main/java/com/ning/billing/recurly/model/TaxTypes.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/model/TestAdjustment.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
This is going into the API version 2.5 branch which is being held off until 2.5 is stable. These are some read only attributes and it only applies to sites with a special Vertex tax integration (which will only be one starting at the turn of the year).
> Vertex Integration

- .gitignore
- src/main/java/com/ning/billing/recurly/model/Coupon.java
- src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
- src/test/java/com/ning/billing/recurly/model/TestCoupon.java
This should resolve #162 by bringing coupon up-to-date with current API spec 2.4 and add temporal duration support.
> Add temporal duration for coupons

- src/test/java/com/ning/billing/recurly/TestUtils.java
This fixes the integration test. I had unfortunately added a static datetime for deliver_at but that value needs to always be 1 hour in the future. This sets it to 5 days from the day of running.
> Fix integration test by ensuring giftcard.deliver_at always in future

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
This adds support for invoices which may have prefixes. It builds on #148 by only accepting invoice ids as Strings for every invoice method. We are also now parsing `invoice_number_prefix` and including it in a new method `getId()` that returns the prefixed or non prefixed id. Example:
```java
final Invoice invoice = new Invoice();
Assert.assertNull(invoice.getId());
invoice.setInvoiceNumber(9999);
Assert.assertEquals(invoice.getId(), "9999");
invoice.setInvoiceNumberPrefix("FR");
Assert.assertEquals(invoice.getId(), "FR9999");
```
I've deprecated all methods using an `Integer` for invoiceId and added new methods using `String`. These are all `RecurlyClient` instance methods:
* getInvoice(Integer invoiceId) => getInvoice(String invoiceId)
* getInvoicePdf(Integer invoiceId) => …
> Fully support Invoice prefixes (and deprecate using integer as invoice id)

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Adjustment.java
- src/main/java/com/ning/billing/recurly/model/AdjustmentRefund.java
- src/main/java/com/ning/billing/recurly/model/InvoiceRefund.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
This adds line item invoice refunds as discussed in #169 . https://dev.recurly.com/docs/line-item-refunds
You have to pass in a list of `AdjustmentRefund`s because they have some fields that don't really belong in `Adjustment`. I've created a convenience method for turning an `Adjustment` into an `AdjustmentRefund`.  You can see the integration test to get an idea how to use it.
```java
final invoice = recurlyClient.getInvoice("1234");
final ArrayList<AdjustmentRefund> lineItems = new ArrayList<AdjustmentRefund>();
// let's just refund the first adjustment
// we can use "toAdjustmentRefund" on the adjustment to turn it
// into an AdjustmentRefund  
final AdjustmentRefund adjustmentRefund = invoice.getLineItems().get(0).toAdjustmentRefund();
// we could change the quantity here or the …
```
> Support line item refunds

- src/main/java/com/ning/billing/recurly/model/Adjustment.java
- src/main/java/com/ning/billing/recurly/model/Transaction.java
- src/test/java/com/ning/billing/recurly/model/TestAdjustment.java
- src/test/java/com/ning/billing/recurly/model/TestTransaction.java
This adds `product_code` on Transaction and Adjustment as needed for Vertex integration.
> Add product_code for Vertex integration

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/RecurlyObjects.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
This is a new change in API version 2.6 and is going into the `api_version_2_6` branch.
We no longer return `X-Records` on every page. Instead, if you wish to get the count you must explicitly call the server with a `HEAD` request and parse the `X-Records` header.
This will be a breaking change because we no longer will support `RecurlyObjects#getNbRecords()`.
The integration tests will be healed by this: https://github.com/killbilling/recurly-java-library/pull/188
> Remove X-Records parsing and add count methods

- pom.xml
- travis-test.sh
It seems that for repo owners (@pierre and myself), travis was only running the integration group. This makes sure we run every test group in travis when the keys are available to do so.
> Change travis profile to run all test groups

- src/main/java/com/ning/billing/recurly/model/Account.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestAccount.java
Resolves #193 
It looks like the `vat_number` field was never added to the `Account` model. This adds that field to the model and tests.
> Add vat_number to Account

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Purchase.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestPurchase.java
Another 2.6 change. The `/purchases` endpoint allows you to build up a bunch of resources to send all at once and returns a new `Invoice`. For now we are just supporting `Account` (new or existing) and a list of `Adjusments`. In 2.7 we will add support for multiple `Subscriptions`, `GiftCards`, and `Coupons`.
> Purchases [API v2.6]

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Purchase.java
- src/main/java/com/ning/billing/recurly/model/RecurlyObjects.java
- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestPurchase.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
Here we have all the changes required to get master up to API Version 2.6. Note that there are 2 breaking changes:
1. `RecurlyObjects#getNbRecords` is not longer supported. We removed the X-Records header from the pagination responses which greatly improves response times. https://github.com/killbilling/recurly-java-library/commit/50dfa32778af4fb6ba214a14515801e7a47ca0b7#diff-eab0eaf4b89b6e014e97fb7ca9d7fd4dL102
2. For `POST /v2/subscriptions` Sending `null` for `total_billing_cycles` attribute will now override plan `total_billing_cycles` setting and will make subscription renew forever.  Omitting the attribute will cause the setting to default to the value of plan `total_billing_cycles`.
- Changed Plan request/response:
- Added `<trial_requires_billing_info>` element.
- Changed …
> API Version 2.6 Changes

- src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
- src/test/java/com/ning/billing/recurly/model/TestSubscriptionUpdate.java
Currently, there is no way to add a coupon when updating a subscription. In order to transfer to a subscription with a coupon, users need to terminate the existing subscription and create a new one.
This PR adds the field for the supported coupon_code attribute on subscription updates.
> Add coupon_code to SubscriptionUpdate

- src/main/java/com/ning/billing/recurly/model/AddOn.java
- src/main/java/com/ning/billing/recurly/model/Adjustment.java
- src/main/java/com/ning/billing/recurly/model/Plan.java
- src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
- src/main/java/com/ning/billing/recurly/model/RevenueScheduleType.java
- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/test/java/com/ning/billing/recurly/model/TestRevenueScheduleType.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
- Earlier `Plan`, `Subscription`, `Addon` and `Adjustment` serialized `RevenueScheduleType` incorrectly. 
- `getRevenueScheduleType()` returned the enum constant for serialization but Recurly expects lower-cased values of the enums
- Centralized the enum serialization deserialization on the class itself
> Fix revenue schedule type xml serialization and deserialization

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Purchase.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/model/TestPurchase.java
This adds the new fields to the `Purchase` object.
- Changed `POST /v2/purchases` request:
- Added `coupon_codes`
- path: `<coupon_codes type="array"><coupon_code>COUPON1234</coupon_code></coupon_codes>`
- description: A list of coupon codes to apply to this purchase.
- Added `subscriptions`
- path: `<subscriptions type="array"><subscription/></subscriptions>`
- description: A list of Subscriptions to invoice in this purchase (currently only one subscription is allowed).
- Added `gift_card`
- path: `<gift_card><redemption_code>ABCD1234</redemption_code></gift_card>`
- description: A gift card with a redemption code to apply to this purchase.
> Bumps to API v2.7

- src/main/java/com/ning/billing/recurly/model/Redemption.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestRedemption.java
Context:
As per https://dev.recurly.com/docs/redeem-a-coupon-before-or-after-a-subscription, the Recurly API supports the ability to pass in a subscription_uuid as part of the request to redeem a coupon. I noticed that there was no ability to do that through this library, so I implemented that ability. Please let me know if there are any changes you'd like me to make as part of code review and I'd be happy to add them. I've run the test suite locally and everything passes.
> Add ability to set subscription UUID when redeeming a coupon

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
We defined this constant but were not using it which could cause a mistake if changed. Decided to use it rather than remove it.
> Use unused X-Records constant

- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/main/java/com/ning/billing/recurly/model/Purchase.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestPurchase.java
**NOTE**: The tests will pass for this on Thursday or Friday. We can hold off until then.
This is for API v2.8 and is only going into the `api_version_2_8` branch for now.
* Added the ability to set custom invoice notes on the `Purchase` object. It seems we missed adding this in `Invoice` in a previous version so I added them there too.
* Updated the tests to use valid 2 character ISO 3166 country codes (which we now validate).
* Fixed a mistake I made in the `TestPurchase` file. We were not properly deserializing and testing the purchase object.
> Custom Invoice Notes, ISO 3166 country codes

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
This PR contains the changes needed for API version 2.9.
1. Added the `authorize` endpoint for purchases. This endpoint allows collection with an external HPP. Currently only Adyen supported and we're still in beta.
2. Any subscription endpoint now accepts the `started_with_gift` parameter to filter out subscriptions that started with a gift card.
```java
final QueryParams params = new QueryParams();
params.put("started_with_gift", true);
```
There are breaking changes with the links in the XML API, however this library does not use the links so there should be no breaking changes this release.
> API Version 2.9

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/TransactionError.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
Fixes 2 failing integration tests. The failure around
https://github.com/killbilling/recurly-java-library/compare/fix_some_integration_tests?expand=1#diff-87440af3c76e58622209127dd94004edR79
could possibly be experienced as a bug when that field is null
> Fix integration tests

- .gitignore
- pom.xml
See discussion at https://github.com/killbilling/recurly-java-library/issues/187.
Note that the library jar is now 1.8M.
@bhelx Do you have a project handy using this library for testing?
> pom.xml: shade Jackson artifacts

- src/main/java/com/ning/billing/recurly/model/Coupon.java
Resolves #235 
Issue:
`com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of com.ning.billing.recurly.model.Coupon$Type from String value 'unique_code': value not one of declared Enum instance names: [single_code, bulk]`
> support coupon enum type unique_code

- src/main/java/com/ning/billing/recurly/model/Purchase.java
For API version 2.13. Allows programmer to set the gateway for a purchase. If this changes, I will follow up with another PR on the `api_version_2_13` branch.
> Allow programmer to set gateway code in purchase

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
This is for API version 2.13. This endpoint can be used to fetch all the transactions on the invoice. Normally they are embedded in the invoice, but in the case where there are more than 500, you must use this endpoint to paginate them.
> Add /transactions endpoint for invoices

- src/main/java/com/ning/billing/recurly/model/Redemption.java
- src/test/java/com/ning/billing/recurly/model/TestRedemptions.java
Issue: coupon code field is not supported in the `Redemption` model. 
Link: https://dev.recurly.com/docs/coupon-redemption-object
Sample payload:
```<?xml version="1.0" encoding="UTF-8"?>
<redemptions type="array">
<redemption href="https://your-domain.recurly.com/v2/accounts/123/redemptions/123456">
<coupon href="https://your-domain.recurly.com/v2/coupons/special"/>
<account href="https://your-domain.recurly.com/v2/accounts/123"/>
<uuid>123456</uuid>
<single_use type="boolean">true</single_use>
<total_discounted_in_cents type="integer">0</total_discounted_in_cents>
<currency>USD</currency>
<state>active</state>
<coupon_code>special</coupon_code>
<created_at type="datetime">2017-03-25T22:18:23Z</created_at>
<updated_at type="datetime">2017-03-25T22:18:23Z</updated_at>
</redemption> …
```
> Support coupon code field in GET account's coupon redemptions

- src/main/java/com/ning/billing/recurly/model/Subscription.java
The setAutoRenew function in subscription has the wrong parameter name.
> fix autoRenew parameter

- README.md
This always says the build is failing and I can't figure out why. It's
makes it look like the master build has always failed even though it
hasn't. I'd rather remove this than fix it.
> Remove travis badge from readme

- src/main/java/com/ning/billing/recurly/model/SubscriptionNotes.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
This is for API version 2.14. Adds Custom Fields support on `updateNotes`.
> Add Custom Fields support to updateNotes

- src/main/java/com/ning/billing/recurly/model/push/invoice/PushInvoice.java
- src/test/java/com/ning/billing/recurly/model/push/TestNotification.java
Fixes #286 
The new Credit and Charge invoice webhooks provide an array of subscription IDs rather than a single subscription ID. This adds support for that new array.
> Add support for subscription ids array in invoice related webhooks

- pom.xml
- src/main/java/com/ning/billing/recurly/RecurlyClient.java
I noticed some compiler warnings when building the project that I wanted to address.
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.ning.billing:recurly-java-library:jar:0.20.1-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ line 367, column 32
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[WARNING] Javadoc Warnings
[WARNING] javadoc: warning - Error fetching URL: http://commons.apache.org/lang/api/
[WARNING] …
```
> Fix warnings given by compiler

- src/main/java/com/ning/billing/recurly/model/SubscriptionState.java
Hey again!
Stumbled upon the subscription state is missing `paused`, as I need to use this state in our code base.
Available states is pulled from docs https://dev.recurly.com/docs/list-subscriptions
Thanks again!
> Support paused subscription state

- src/main/java/com/ning/billing/recurly/ConnectionErrorException.java
- src/main/java/com/ning/billing/recurly/RecurlyClient.java
Fixes #185 
To test, configure the RecurlyClient to attempt to connect to an unsupported port (such as 81) and you will reliably get a "Connection Refused" error, which is an instance of `java.net.ConnectException`. A timeout error is also a `java.net.ConnectException`, though I haven't found a reliable way to test that particular one. If anyone has suggestions on a setup where a timeout can be reliable generated, please feel free to comment.
> Rethrow ConnectExceptions as runtime exceptions

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Adjustment.java
- src/main/java/com/ning/billing/recurly/model/InvoiceRefund.java
- src/main/java/com/ning/billing/recurly/model/RefundMethod.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
Deprecating current way of doing refunds for a single refund method
which now supports all possible options.
This is not a breaking change but does deprecate the current methods for doing refunds on Invoices.
In order to do refunds now, the programmer should use the `InvoiceRefund` object:
```java
final InvoiceRefund refundOptions = new InvoiceRefund();
refundOptions.setRefundMethod(RefundMethod.transaction_first);
refundOptions.setAmountInCents(100);
refundOptions.setCreditCustomerNotes("Credit Customer Notes");
refundOptions.setExternalRefund(true);
refundOptions.setPaymentMethod("credit_card");
final Invoice refundInvoice = recurlyClient.refundInvoice(invoice.getId(), refundOptions);
```
> Update refund calls to support credit memos

- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionNotes.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
This allows you to change the gateway code via the subscription `/notes` endpoint as well as the `PUT invoice` endpoint.
Script:
```java
try {
client.open();
// Subscription Notes
final SubscriptionNotes subscriptionNotesData = new SubscriptionNotes();
subscriptionNotesData.setGatewayCode("jqgayw0mjh5w");
Subscription sub = client.updateSubscriptionNotes("4810fde9f3f29b244474e445d795cc78", subscriptionNotesData);
// Invoice
Invoice updatedInvoice = new Invoice();
updatedInvoice.setGatewayCode("jvm7v7as5ugm");
client.updateInvoice("1001", updatedInvoice);
e.printStackTrace();
} finally {
}
```
> Add gatewayCode to subscription notes and invoice

- src/main/java/com/ning/billing/recurly/model/Account.java
- src/test/java/com/ning/billing/recurly/model/TestAccount.java
Adds exemption_certificate attribute to the account object.
Script:
```java
try {
client.open();
final Account account = new Account();
account.setAccountCode("new-account");
account.setTaxExempt(true);
account.setExemptionCertificate("Some Certificate");
client.createAccount(account);
System.out.println(e.getStackTrace());
} finally {
}
```
> Add exemption certificate to Account

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
Fixes #297 
NOTE: This is not thread safe. Consider the following situation:
```java
// in user 1's thread
client.setAcceptLanguage('de')
client.createSubscription()
```
```java
// in user 2's thread
client.setAcceptLanguage('en-US')
client.createSubscription()
```
These operations could interleave, such that `setAcceptLanguage()` gets called twice before the calls to `createSubscription()` are ever called. Meaning that if something went wrong with one of the requests, it would not be possible to guarantee that their error message would be in the correct language.
If your implementation takes advantage of threading (as most modern Java implementations do), you may experience problems by using this method in the above fashion. Please take all necessary caution to ensure that the client …
> Add setAcceptLanguage method

- src/main/java/com/ning/billing/recurly/model/Adjustment.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/model/TestPurchase.java
Fixes #301 
This adds a method called `getSubscriptionId` to the Adjustment. Not all adjustments have a `subscription` tag, so it returns null if irrelevant.
Script:
```java
try {
client.open();
final Account accountData = new Account();
accountData.setAccountCode("bklalskjalg");
final BillingInfo billingInfoData = new BillingInfo();
billingInfoData.setFirstName("Benjamin");
billingInfoData.setLastName("Du monde");
billingInfoData.setAddress1("124 main st");
billingInfoData.setCity("New York");
billingInfoData.setState("CA");
billingInfoData.setZip("94110");
billingInfoData.setCountry("US");
billingInfoData.setYear(2020);
billingInfoData.setMonth(12);
billingInfoData.setNumber("4111 1111 1111 1111");
billingInfoData.setVerificationValue(123);
accountData.setBillingInfo(billingInfoData); …
```
> Add getSubscriptionId() to Adjustment for Purchases endpoint

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
This PR adds a method for this API endpoint: https://dev.recurly.com/docs/lookup-a-coupon-redemption-on-a-subscription
Script:
```java
// Assumes sub uuid "466150990318962b8cfabb4513896cd5" exists on account
// and has a coupon redemption associated with it
import com.ning.billing.recurly.QueryParams;
import com.ning.billing.recurly.model.Redemptions;
public class ListCouponRedemptions {
try {
client.open();
final String subUuid = "466150990318962b8cfabb4513896cd5";
Redemptions red = client.getCouponRedemptionsBySubscription(subUuid, new QueryParams());
System.out.println(red);
e.printStackTrace();
} finally {
}
}
}
```
> Add method to list coupon redemptions by subscription

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Coupon.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
This library was missing methods for handling these two API endpoints. This PR adds those methods.
https://dev.recurly.com/docs/generate-unique-codes
https://dev.recurly.com/docs/list-unique-coupon-codes
Script:
```java
import com.ning.billing.recurly.model.Coupon;
import com.ning.billing.recurly.model.Coupons;
import com.ning.billing.recurly.model.Coupon.DiscountType;
import com.ning.billing.recurly.QueryParams;
public class ListUniqueCodes {
try {
client.open();
String couponCode = "thankyou";
Coupon newCoupon = new Coupon();
newCoupon.setType(Coupon.Type.bulk);
newCoupon.setDiscountType(DiscountType.percent);
newCoupon.setDiscountPercent(10); …
```
> Add methods to generate and list bulk coupons

- src/main/java/com/ning/billing/recurly/model/Coupon.java
- src/main/java/com/ning/billing/recurly/model/PlanCode.java
- src/main/java/com/ning/billing/recurly/model/PlanCodeSerializer.java
- src/main/java/com/ning/billing/recurly/model/PlanCodes.java
- src/main/java/com/ning/billing/recurly/model/PlanCodesSerializer.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/model/TestCoupon.java
- src/test/java/com/ning/billing/recurly/model/TestCoupons.java
- src/test/java/com/ning/billing/recurly/model/TestSubscriptions.java
This fixes https://github.com/killbilling/recurly-java-library/issues/244.
Any idea for the `must_apply_to_plans_or_non_plan_charges` error on Travis?
> coupon: fix plan_codes parsing

- README.md
Recurly has not supported TLS 1.1 since July 2018. See https://dev.recurly.com/page/tls-v10-deprecation
Recurly.js v4 does not require signatures using the private key. See https://dev.recurly.com/docs/recurlyjs
> Update README based on current technologies

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Account.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestAccount.java
This adds support for the Account Hierarchy feature. The integration test is not included because the API version has not been released yet. Unit tests are updated. Please see below for example usage.
Create an account with a parent account:
```java
// Assumes account "example-124" exists
try {
client.open();
final Account account = new Account();
account.setAccountCode("example-123");
account.setParentAccountCode("example-124");
client.createAccount(account);
System.out.println(e.getStackTrace());
} finally {
}
```
Update an account to add a parent account:
```java
// Assumes "example-123" and "example-124" exist
// Assumes that "example-124" is not already the parent of "example-123"
try {
client.open();
final Account account = new Account(); …
```
> Add support for account hierarchy

- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java
This adds support for Amazon Pay.
```java
import com.ning.billing.recurly.model.BillingInfo;
public class CreateBillingInfo {
try {
client.open();
billingInfo.setFirstName("John");
billingInfo.setLastName("Smith");
billingInfo.setAddress1("125 Paper Street");
billingInfo.setCity("Los Angeles");
billingInfo.setState("CA");
billingInfo.setZip("95312");
billingInfo.setCountry("US");
billingInfo.setPhone("213-555-5555");
billingInfo.setAmazonBillingAgreementId("C02-2000965-4255444");
billingInfo.setAmazonRegion("us");
client.createOrUpdateBillingInfo(billingInfo); …
```
> Add support for Amazon Pay to Billing Info

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/RecurlyAPIError.java
- src/main/java/com/ning/billing/recurly/model/ResponseMetadata.java
If a user gets exceptions, they will now see the Recurly request id and/or the cloudflare request id. This is useful for debugging esp at the cloudflare layer. This can be expanded on in the future, for now I'm keeping it to solving the particular problem he had.
To test, create an error (such as a 404) and check that the log contains the request id and the cf_ray id.
> Adds request identifiers to errors

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
Theoretically, no merchants should have logging enabled in production. However, in the other client libraries, we go ahead and give a warning when the logger is enabled. This will log a similar warning so that if anyone has debug mode on in production, they are aware of the PII consequences (and are hopefully inspired to turn off debugging of production data).
> Add a warning about logging PII in production

- src/main/java/com/ning/billing/recurly/model/InvoiceState.java
The docs [here](https://dev.recurly.com/docs/list-invoices) show that there are more available invoice states than what was currently in the library. This updates the InvoiceState enum to allow for the more recent states.
Script:
```java
import com.ning.billing.recurly.QueryParams;
import com.ning.billing.recurly.model.Invoices;
import com.ning.billing.recurly.model.InvoiceState;
public class GetAccountInvoices {
try {
client.open();
String accountCode = "x";
InvoiceState state = InvoiceState.PAID;
QueryParams params = new QueryParams();
Invoices accountInvoices = client.getAccountInvoices(accountCode, state, params);
System.out.println(accountInvoices);
} catch …
```
> Add more invoice states in accordance with the docs

- src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
Jackson version 2.7.4 and above disable XML external entity processing (XXE) by default. Since we're still using 2.5.0, we have to manually disable XXE.
> Disable External Entities from XmlMapper

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java
This adds support for API version 2.18 features:
* Amazon Region, for use with Amazon Pay UK [PR](https://github.com/killbilling/recurly-java-library/pull/316)
> Release API version 2.18

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
The other Recurly clients all validate that the domain requests are being made to is "recurly.com". This adds a check to verify the same is true in this library.
Testing:
Initialize a RecurlyClient with the "subdomain" as `maliciousdomain.com/`. See how the client now blocks requests from being made to that malicious domain.
> Validate all API calls are being made to recurly.com

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
Fixes #326 
Print just the account code if the account's billing info is set to the same object as the billing info to prevent an infinite when there's a circular reference.
Script:
```java
final Account account = new Account();
account.setAccountCode("b");
final BillingInfo info = new BillingInfo();
// create a circular reference
account.setBillingInfo(info);
info.setAccount(account);
System.out.println(account); // now this does not throw an exception
```
> Fix stackoverflow exception

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
If you enter an empty string into certain RecurlyClient methods, the API will return all of that resource. E.g.,
```java
Account account = client.getAccount("");
```
This can lead to information disclosure in certain situations and should not be allowed.
> Throw errors when input is empty

- src/main/java/com/ning/billing/recurly/model/Plan.java
- src/test/java/com/ning/billing/recurly/model/TestPlan.java
Fixes #333 and #334 
Example with tax code and tax exempt:
```java
client.open();
final Plan plan = new Plan();
plan.setPlanCode("new-plan");
plan.setName("New Plan");
final RecurlyUnitCurrency price = new RecurlyUnitCurrency();
price.setUnitAmountUSD(10);
plan.setUnitAmountInCents(price);
plan.setTaxCode("unknown");
plan.setTaxExempt(true);
client.createPlan(plan);
```
The parameter name for `setAutoRenew` is also fixed, but the interface is the same so it's not in the example.
> Add tax_exempt and tax_code to Plan

- src/main/java/com/ning/billing/recurly/model/AbstractAddOn.java
- src/main/java/com/ning/billing/recurly/model/AddOn.java
- src/main/java/com/ning/billing/recurly/model/Adjustment.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionAddOn.java
- src/main/java/com/ning/billing/recurly/model/TaxDetail.java
- src/test/java/com/ning/billing/recurly/model/TestAddOns.java
- src/test/java/com/ning/billing/recurly/model/TestAdjustment.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
Fixes #338 and fixes #339 
There were some missing properties in the `AddOn`, `SubscriptionAddOn` and `Adjustment` classes. This PR adds those missing properties and adds them to the unit tests.
> Fix missing values in add ons

- src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
This adds support for updating the subscription at next bill date rather than just immediately or at renewal.
```java
final String uuid = "4c2a90c55cfe520e7f33744dc09ae922";
final SubscriptionUpdate subscriptionData = new SubscriptionUpdate();
subscriptionData.setTimeframe(SubscriptionUpdate.Timeframe.bill_date);
subscriptionData.setPlanCode("gold");
Subscription sub = client.updateSubscription(uuid, subscriptionData);
System.out.println(sub);
```
> Add support for updating subscription at next bill date

- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
Fixes #341 
This adds all of the missing values that are listed in the documentation on this page https://dev.recurly.com/docs/update-subscription
script:
```java
try {
client.open();
final String uuid = "4c20e870ad704fe5c6aa0c41c7b494e7";
final SubscriptionUpdate subscriptionData = new SubscriptionUpdate();
subscriptionData.setNetTerms(30);
subscriptionData.setPoNumber("12345");
subscriptionData.setRevenueScheduleType(RevenueScheduleType.EVENLY);
subscriptionData.setRemainingBillingCycles(1);
subscriptionData.setImportedTrial(true);
subscriptionData.setRenewalBillingCycles(2);
subscriptionData.setAutoRenew(false);
final Subscription sub = client.updateSubscription(uuid, subscriptionData);
System.out.println(sub);
e.printStackTrace();
} finally {
} …
```
> Add missing values from SubscriptionUpdate class

- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/main/java/com/ning/billing/recurly/model/TransactionError.java
This allows the client to use the new 3DSecure features of the API. This involves a 2 step flow with RecurlyJS, see https://github.com/recurly/recurly-js/pull/527 for technical details on that side of this process.
Script 1: Attempt to update a billing info with a credit card that requires 3DS authentication:
```java
try {
client.open();
billingInfo.setFirstName("John");
billingInfo.setLastName("Smith");
billingInfo.setAddress1("125 Paper Street");
billingInfo.setCity("Los Angeles");
billingInfo.setState("CA");
billingInfo.setZip("95312");
billingInfo.setCountry("US");
billingInfo.setPhone("213-555-5555");
billingInfo.setNumber("4000000000003220");
billingInfo.setMonth(12);
billingInfo.setYear(20); …
```
> Add 3DS tokens to transaction error and billing info

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/main/java/com/ning/billing/recurly/model/TransactionError.java
This will bring us up to API version 2.21. There are no breaking changes.
* Adds support for 3DS authentication #346
Note: This API version corrects the error of an invalid Recurly.js token sent to `v2/accounts/:account_code/billing_info` from a `404 Not Found` to a `422 Unprocessable Entity`
> Bump to API version 2.21

- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
Fixes #349 
The root cause of the problem described in #349 is as follows:
The Recurly v2 API Create Subscription and Preview Subscription endpoints accept both a single coupon code, e.g.
```xml
<coupon_code>my-coupon</coupon_code>
```
and multiple coupon codes, e.g.
```xml
<coupon_codes>
<coupon_code>my-coupon</coupon_code>
<coupon_code>my-other-coupon</coupon_code>
<coupon_codes>
```
As such, there are two fields in the `Subscription` class:
```java
private String couponCode;
```
and
```java
private List<String> couponCodes;
```
FasterXML Jackson only allows for one field to be associated with the tag `<coupon_code>` as documented by this issue https://github.com/FasterXML/jackson-dataformat-xml/issues/192
This PR gets around this limitation by having Jackson ignore the field …
> Fix multiple coupon codes

- src/main/java/com/ning/billing/recurly/model/Account.java
The `toString` implementation had an extra apostrophe for parent account
code, so it would show up as: `parent_account_code=''null'`
> Fix duplicate apostrophe in Account's toString

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Account.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
Also adds the `closed_at` field from the XML to the Account object,
and fixes up some inconsistencies (underscores instead of camelcase)
in the `toString` implementation.
> Add method for reopening a closed account

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Account.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/main/java/com/ning/billing/recurly/model/Purchase.java
- src/main/java/com/ning/billing/recurly/model/Subscription.java
As a part of PSD2, there is an exemption to exclude MOTO transactions from SCA scope.
In order to pass this indicator to the gateways, merchants need a mechanism via API
to inform Recurly of these transactions. These transactions will be initiated from
within a merchants customer service / support admin portal UI, where the customer
is not authenticated to be able to complete an SCA flow.
This is exposed to the programmer as transaction_type on many of the resources. Set the value to moto to mark the transaction as MOTO. Ex use with purchases:
```java
final Purchase purchaseData = new Purchase();
purchaseData.setCurrency("USD");
purchaseData.setTransactionType("moto");
purchaseData.setAccount(accountData);
purchaseData.setSubscriptions(subscriptionsData);
InvoiceCollection collection = …
```
> MOTO transactions

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
Sometimes 422 errors can return a single error rather than multiple (for
example, on invalid billing token). This changes the deserialization
logic to attempt reading the response as a single error if the original
attempt fails.
Fixes #354
> Fix deserialization of 422 invalid token error

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
- src/test/java/com/ning/billing/recurly/model/TestSubscriptionUpdate.java
WIP: i've broken something around url building.
Adds term_end to the Timeframe values. This affects updateSubscription
and cancelSubscription.
updateSubscription has been updated to no longer include the "renewal" timeframe.
Instead, merchants will be able to send timeframes of "bill_date" or "term_end".
These timeframes are aligned to "current_period_ends_at" and "current_term_ends_at", respectively.
cancelSubscription has been updated to accept the "timeframe" parameter. They accept values of "bill_date" or "term_end".
> [WIP] Add term_end timeframe value

- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java
Hello Killbilling Team!
Thank you for the continued support on this SDK.
Please find attached change to support ACH fields on [BillingInfo API](https://dev.recurly.com/docs/create-an-accounts-billing-info-credit-card). Specifically, I have added the fields:
* `name_on_account`
* `account_type`
* `routing_number`
* `account_number`
This is a sample API response:
```
<?xml version="1.0" encoding="UTF-8"?>
<billing_info href="https://dev.recurly.com/v2/accounts/123456/billing_info" type="bank_account">
<account href="https://dev.recurly.com/v2/accounts/123456"/>
<name_on_account>Watson Reseller</name_on_account>
<first_name nil="nil"></first_name>
<last_name nil="nil"></last_name>
<company></company>
<address1>4225 executive square</address1>
<address2></address2>
<city>la jolla</city> …
```
> Support ACH fields on BillingInfo

- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
Fixes we missed in review here. These parameters need to be `Object`s. https://github.com/killbilling/recurly-java-library/pull/367
> Some fixes for setters

- src/main/java/com/ning/billing/recurly/model/ShippingAddress.java
`vatNumber` is a supported attribute for `ShippingAddress` but has not yet been included in the Java client library. This PR addresses that issue.
> Add `vatNumber` to ShippingAddress class

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
In response to https://github.com/killbilling/recurly-java-library/issues/362
```java
/**
* Return all the subscriptions on an invoice.
*
* @param invoiceId String Recurly Invoice ID
* @return all the subscriptions on the invoice
*/
public Subscriptions getInvoiceSubscriptions(final String invoiceId) {
return getInvoiceSubscriptions(invoiceId, new QueryParams());
}
/**
* Return all the subscriptions on an invoice.
*
* @param invoiceId String Recurly Invoice ID
* @param params {@link QueryParams}
* @return all the subscriptions on the invoice
*/
public Subscriptions getInvoiceSubscriptions(final String invoiceId, final QueryParams params) {
return doGET(Invoices.INVOICES_RESOURCE + "/" + invoiceId + Subscriptions.SUBSCRIPTIONS_RESOURCE,
Subscriptions.class, params);
}
```
> Add getInvoiceSubscriptions to RecurlyClient

- src/main/java/com/ning/billing/recurly/model/GiftCard.java
Addresses [issue 376](https://github.com/killbilling/recurly-java-library/issues/376).
The following fields were missing from the GiftCard model: 
`gifterAccountCode`
`recipientAccountCode`
`invoiceNumber`
> Add attributes to GiftCard model

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
The `getCouponRedemptionsByInvoice` method for some reason uses `/subscription` instead of `/subscriptions`.
> Fix getCouponRedemptionsByInvoice

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
This feature is to allow support of the IBAN field in our V2 API for the applicable endpoints. This field is most similar to banking account information or credit card information, and is used to make payments for SEPA transactions.
IBAN numbers can be set in all endpoints that support BillingInfo:
PUT "/v2/accounts/{account_id}/billing_info"
PUT "/v2/accounts/{account_id}"
POST "/v2/accounts"
POST "/v2/subscriptions"
POST "/v2/purchases"
POST "/v2/purchases/preview"
A sample request payload is provided below:
```
<billing_info>
<iban>IBANNUMBERHERE</iban>
<name_on_account>Verena Example</name_on_account>
<!-- address fields... ->
</billing_info>
```
> Add IBAN attribute to BillingInfo

- src/main/java/com/ning/billing/recurly/model/AddOn.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestItemBackedAddOns.java
To create item-backed add-on:
```java
final AddOn addon1 = new AddOn();
addon1.setItemCode(item.getItemCode());
final RecurlyUnitCurrency price = new RecurlyUnitCurrency();
price.setUnitAmountUSD(10);
addon1.setUnitAmountInCents(price);
final AddOn addon2 = client.createPlanAddOn(plan.getPlanCode(), addon1);
```
To get item-backed add-on:
```java
final AddOn addon = client.getAddOn(plan.getPlanCode(), item.getItemCode());
```
To update item-backed add-on:
```java
AddOn addOnData = new AddOn();
addOnData.setDefaultQuantity(5);
final AddOn updatedAddOn = client.updateAddOn(plan.getPlanCode(), addon.getAddOnCode(), addOnData);
```
When add-on has an associated item, only the following attributes are updatable:
```java
unit_amount_in_cents
default_quantity
display_quantity_on_hosted_page …
```
> Enable item-backed add-ons

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
A mandate reference is a specific ID used in a payment system to show that an agreement was made between the customer and the merchant. It is often required for compliance reasons to display when a billing info is created or a payment is created.
> Add mandateReference attribute to BillingInfo

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
I've run into an issue using this library where account codes with spaces and special characters wouldn't work. And the apparent cause was that URL path segments are not getting URL encoded. So I went ahead and added URL encoding to all the path segments. The behavior should not change for Strings without special characters.
> Add URL encoding to URL path segments

- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
These `catches` had the potential to swallow the exceptions and not fail the tests.
> Prevent unexpected exceptions from being swallowed in tests

- pom.xml
- src/main/java/com/ning/billing/recurly/QueryParams.java
- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/RecurlyAPIError.java
- src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
- src/main/java/com/ning/billing/recurly/model/ResponseMetadata.java
- src/main/java/com/ning/billing/recurly/model/push/Notification.java
As you probably know, I've created a few smaller pull requests in the past, and those were actually brought over from my fork, which is what we use today on production at SaaSquatch.
The pull request you see here represents the entirety of my fork, which is at this moment up and running on SaaSquatch servers, and has been battle tested for over a year without any issue.
While my previous smaller pull requests mainly focus on fixing obvious bugs and issues, this large pull request mainly aims to "modernize" this library to make it work well on a modern environment, as well as to make some minor improvements.
Here are some key points:
- Even though I said the word "modernize", this fork still targets Java 6.
- The outdated version of async-http-client (hereinafter referred to as AHC) has …
> Replace IO layer to use Apache HC + trivial cleanups

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java
Added `sort_code` and `type` fields to support BACS payment type.
Previously, the `type` field was a xml attribute with a protected setter. When BACS is the payment option, however, `type` must accept `"bacs"` as a value.
> Add BACS support

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Plan.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionAddOn.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
This PR adds support for items on subscriptions, where merchants may now associate a subscription add-on with an item in their catalog.
`allow_any_item_on_subscriptions` has been added to the `Plan` class. It is used to determine whether items can be assigned as add-ons to individual subscriptions. If `true`, items can be assigned as add-ons to individual subscription add-ons. If `false`, only plan add-ons can be used.
`add_on_source`, added to the `SubscriptionAddOn` class, is used to determine where the associated add-on data is pulled from. If this value is set to `plan_add_on` or left blank, then add-on data will be pulled from the plan's add-ons. If the associated  `plan` has `allow_any_item_on_subscriptions` set to `true` and this field is set to `item`, then the associated add-on …
> Support items on subscriptions

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
I recently noticed that Apache Commons Codec is a transitive dependency of Apache HttpClient, so I switched the not-so-great String replace implementation of URL encoding to using the `URLCodec` class in Apache Commons Codec, which is a lot faster than Java's built-in `URLEncoder` even without the String replace.
> URL encoding cleanup

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/RecurlyJs.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestRecurlyJs.java
The `String.format(String, Object...)` method is environment dependent and uses the system's default locale.
Here's a simple example of how that might go wrong:
```java
public static void main(String[] args) {
System.out.println(String.format(new Locale("hi", "IN"), "%d", 1234));
}
```
This will actually print `१२३४` instead of `1234`.
> Explicit locale in String.format

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestBillingInfo.java
Completed:
- Added `bsb_code` field
Affects the following endpoints:
- `PUT /v2/accounts/{account_id}/billing_info`
- `PUT /v2/accounts/{account_id}`
- `POST /v2/accounts`
- `POST /v2/purchases`
- `POST /v2/purchases/preview`
- `POST /v2/subscriptions`
To create billing_info with BECS:
```java
billingInfo.setAccountNumber("12345678");
billingInfo.setType("becs");
billingInfo.setNameOnAccount("BECS Test");
billingInfo.setAddress1("125 Paper Street");
billingInfo.setCity("Adelaide");
billingInfo.setZip("12345");
billingInfo.setCountry("AU");
billingInfo.setType("becs");
billingInfo.setBsbCode("082-082");
client.createOrUpdateBillingInfo(account.getAccountCode(), billingInfo);
```
> BECS support

- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
Allows merchants to specify individual tax identifiers for customers (CPF + Brazil support) when creating and updating billing information.
Two fields introduced:
`tax_identifier`
`tax_identifier_type`
Example code:
```java
billingInfo.setFirstName("John");
billingInfo.setLastName("Smith");
billingInfo.setAddress1("125 Paper Street");
billingInfo.setCity("Los Angeles");
billingInfo.setState("CA");
billingInfo.setZip("95312");
billingInfo.setCountry("US");
billingInfo.setPhone("2135555555");
billingInfo.setNumber("4111111111111111");
billingInfo.setMonth(12);
billingInfo.setYear(20);
billingInfo.setTaxIdentifier("758.356.352-65");
billingInfo.setTaxIdentifierType("cpf");
client.createOrUpdateBillingInfo(account.getAccountCode(), …
```
> Add tax identifier fields to billing info

- src/main/java/com/ning/billing/recurly/model/AbstractAddOn.java
- src/main/java/com/ning/billing/recurly/model/AddOn.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
- Relocate tiers to AbstractAddOn so it is accessible to both AddOn and SubscriptionAddOn
- Add SubscriptionAddOns to SubscriptionUpdate
Note that this change will trigger the following error because `unit_amount_in_cents` is sent as `Recurly::Money` instead of as an `Integer`. This error will be addressed in a separate ticket.
```
<error>
<symbol>invalid_xml</symbol>
<description>The provided XML was invalid.</description>
<details>Tag &lt;unit_amount_in_cents&gt; must contain only text</details>
</error>
```
Sample code:
```java
Tier updateTierData = new Tier();
final RecurlyUnitCurrency updatePrice = new RecurlyUnitCurrency();
updatePrice.setUnitAmountUSD(99);
updateTierData.setUnitAmountInCents(updatePrice);
updateTierData.setEndingQuantity(19);
tiers.set(0, updateTierData); …
```
> Enable updating tiers on subscription add-ons

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/BillingInfoVerification.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
If the account has billing information for anything other than a credit card, this will return 422, with an appropriate error message. If successful, this will return 200, with the transaction's data.
`gateway_code` (optional) is the code for the gateway to use for the verification. If unspecified, a gateway will be selected using the normal rules.
Example
```java
// verify without specifying gateway code to use 
client.verifyBillingInfo(account.getAccountCode());
// verify with a specific gateway code
final BillingInfoVerification gateway = new BillingInfoVerification();
gateway.setGatewayCode("gateway-code");
client.verifyBillingInfo(account.getAccountCode(), gateway);
```
> New endpoint to verify an account's billing information

- src/main/java/com/ning/billing/recurly/model/Coupon.java
- src/main/java/com/ning/billing/recurly/model/ItemCode.java
- src/main/java/com/ning/billing/recurly/model/ItemCodeSerializer.java
- src/main/java/com/ning/billing/recurly/model/ItemCodes.java
- src/main/java/com/ning/billing/recurly/model/ItemCodesSerializer.java
- src/test/java/com/ning/billing/recurly/model/TestCoupon.java
Add `item_codes` and `applies_to_all_items` to Coupon
Example
```java
final Coupon coupon = new Coupon();
coupon.setCouponCode("special");
coupon.setName("Special");
coupon.setDiscountType("percent");
coupon.setDiscountPercent(10);
coupon.setAppliesToAllItems(false);
final ItemCodes itemCodes = new ItemCodes();
final ItemCode itemCode = new ItemCode();
itemCode.setName("one_item");
itemCodes.add(itemCode);
coupon.setItemCodes(itemCodes);
client.createCoupon(coupon);
```
> Support item-specific coupons

- src/main/java/com/ning/billing/recurly/model/AddOn.java
- src/main/java/com/ning/billing/recurly/model/BillingInfo.java
- Because `item_state` and `external_sku` are included in the xml response for item-based add-ons, it would be good practice to expose this fields to the programmer.
- Same applies to `last_two` for `BillingInfo`
> Expose fields in response xml to developer

- src/test/java/com/ning/billing/recurly/TestUtils.java
Integration tests were failing for all tests that involved billing info with cc, as expiry date was configured as 11/20. I changed the expiry year to 2049 to repair the tests.
> Change test cc year so it's no longer expired

- .github/workflows/ci.yml
- .github/workflows/release.yml
The `ubuntu-latest` recently updated from Ubuntu 18.04 to Ubuntu 20.04. As a part of that upgrade, the default java version changed from [1.8.0_282](https://github.com/actions/virtual-environments/blob/ubuntu18/20210131.1/images/linux/Ubuntu1804-README.md#java) to [11.0.10+9](https://github.com/actions/virtual-environments/blob/ubuntu20/20210412.1/images/linux/Ubuntu2004-README.md#java).
This addresses the `error: package javax.xml.bind.annotation does not exist` error in test runs.
> Lock down the github actions virtual environment to Ubuntu 18.04

- .github/workflows/ci.yml
- .github/workflows/release.yml
A cleaner solution than what was done in https://github.com/killbilling/recurly-java-library/pull/426
> Use setup-java action to set Java version in ubuntu-latest

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
According to the doc [Postponing Subscriptions](https://developers.recurly.com/api-v2/v2.29/index.html#operation/postponeSubscriptionOrExtendTrial) should be using the field `next_bill_date ` instead of the deprecated `next_renewal_date`.
> Postpone subscriptions using the next_bill_date field

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- Add `SSLException` to the subset of `IOException` which throw `ConnectionErrorException` rather than warn and return null
- Currently, there is no way to handle `SSLException`, which may be ephemeral and retried, because the exception is swallowed
- Conceptually, `SSLException` is an ephemeral error at the connection level, so the inclusion makes sense
- Practically, most `IOException` instances which aren't re-thrown in this branch are XML-related
> Re-throw SSLException as ConnectionErrorException rather than return null

- src/main/java/com/ning/billing/recurly/model/AccountBalance.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/model/TestAccountBalance.java
Add new add `processingPrepaymentBalanceInCents` attribute to `AccountBalance`. The `processingPrepaymentBalanceInCents` attribute is a similar format to the `balanceInCents` attribute and contains
the total for processing prepayment credit invoices in each currency. This value is useful when trying to determine if the customer's prepayment balance has run out or if it is currently processing while waiting on a payment for the corresponding purchase invoice.
> V2 add processingPrepaymentBalanceInCents to AccountBalance

- src/main/java/com/ning/billing/recurly/model/AbstractRampInterval.java
- src/main/java/com/ning/billing/recurly/model/Plan.java
- src/main/java/com/ning/billing/recurly/model/PlanRampInterval.java
- src/main/java/com/ning/billing/recurly/model/PlanRampIntervals.java
- src/main/java/com/ning/billing/recurly/model/PricingModel.java
- src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
- src/main/java/com/ning/billing/recurly/model/Tier.java
- src/test/java/com/ning/billing/recurly/model/TestPlan.java
Support for Ramp Pricing has been added to the Java client. New models created:
```
PlanRampIntervals
PlanRampInterval
```
Added the following fields to the `Plan` class:
```
pricingModel
rampIntervals
```
A `RampInterval` is defined as having a `startingBillingCycle` and a collection of prices by currency as `unitAmountInCents`
> Added support for creating/updating/viewing Plans with Ramp Pricing

- src/main/java/com/ning/billing/recurly/model/PlanRampInterval.java
- src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
- src/main/java/com/ning/billing/recurly/model/RecurlyUnitCurrency.java
- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionRampInterval.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionRampIntervals.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
We can now create subscriptions with ramp intervals in two ways. Either create a subscription and use a `plan_code` for a plan that has ramp intervals if the default ramps are desired or do the same as above while supplying a new set of ramp intervals.
> Adding support for creating Subscriptions with ramp intervals from a ramp priced plan or custom ramps

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
**Related Items**:
https://github.com/killbilling/recurly-java-library/issues/185
https://github.com/killbilling/recurly-java-library/pull/292
https://github.com/killbilling/recurly-java-library/pull/411
Fixes an issue where the client will return `null` for an operation that encounters a `SocketTimeoutException`.
> Throw an error when a SocketTimeoutException is thrown

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Account.java
- src/main/java/com/ning/billing/recurly/model/CustomerPermission.java
- src/main/java/com/ning/billing/recurly/model/ExternalProduct.java
- src/main/java/com/ning/billing/recurly/model/ExternalProductReference.java
- src/main/java/com/ning/billing/recurly/model/ExternalProductReferences.java
- src/main/java/com/ning/billing/recurly/model/ExternalProducts.java
- src/main/java/com/ning/billing/recurly/model/ExternalResource.java
- src/main/java/com/ning/billing/recurly/model/ExternalSubscription.java
- src/main/java/com/ning/billing/recurly/model/ExternalSubscriptions.java
- src/test/java/com/ning/billing/recurly/model/TestAccountExternalSubscriptions.java
- src/test/java/com/ning/billing/recurly/model/TestExternalProduct.java
- src/test/java/com/ning/billing/recurly/model/TestExternalProducts.java
- src/test/java/com/ning/billing/recurly/model/TestExternalSubscription.java
- src/test/java/com/ning/billing/recurly/model/TestExternalSubscriptions.java
- Add `ExternalProductReference`, `ExternalProductReferences`, `ExternalProduct`, `ExternalProducts`, `ExternalSubscription`, `ExternalSubscriptions` and `ExternalResource` models.
- Add following endpoints to the client:
- /external_subscriptions
- /external_subscriptions/:uuid
- /accounts/:account_code/external_subscriptions
- /external_products
- /external_products/:uuid
> [API v2] Support for external subscriptions.

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/AccountBalance.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
- src/test/java/com/ning/billing/recurly/model/TestAccountBalance.java
Add new `availableCreditBalanceInCents` attribute to `AccountBalance`. The `availableCreditBalanceInCents` attribute is a similar format to the `balanceInCents` attribute and contains the total of open balances for credit invoices in each currency. This value is useful when trying to determine if the customer's account has any available credit that can be applied to an existing collectible invoice on the account.
Add new `applyCreditBalance` method to `Invoice`. This action will be available for collectible charge invoices. If the account has available credit it will be applied to pay down the balance on the invoice.
> Add support for Apply Credit Balance to existing invoice feature

- src/main/java/com/ning/billing/recurly/model/Account.java
- src/test/java/com/ning/billing/recurly/TestUtils.java
Adds `Account#preferred_time_zone` as a string attribute for API version 2.29 which is used to determine the time zone of emails sent on behalf of the merchant to the customer.
> Add `preferred_time_zone` to Account

- src/main/java/com/ning/billing/recurly/model/CustomFieldDefinition.java
- src/main/java/com/ning/billing/recurly/model/CustomFieldDefinitions.java
- src/test/java/com/ning/billing/recurly/model/TestCustomFieldDefinition.java
- src/test/java/com/ning/billing/recurly/model/TestCustomFieldDefinitions.java
https://github.com/killbilling/recurly-java-library/pull/456 introduced 4 new files, but failed to include the license comment block
> Add missing license header block

- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
`Invoice` response format has changed:
- Added `<used_tax_service>`. Field is present if taxes are enabled. Value is `true` or `false` based on a successful response from the tax service.
> Add usedTaxService to Invoice response

- src/main/java/com/ning/billing/recurly/model/Invoice.java
The `usedTaxService` condition for returning `false` should have reference `invoice` instead of `that`.
> Corrected typo in Invoice

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/Account.java
- src/main/java/com/ning/billing/recurly/model/BusinessEntities.java
- src/main/java/com/ning/billing/recurly/model/BusinessEntity.java
- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/main/java/com/ning/billing/recurly/model/InvoiceDisplayAddress.java
- src/main/java/com/ning/billing/recurly/model/RecurlyObject.java
- src/main/java/com/ning/billing/recurly/model/TaxAddress.java
- src/test/java/com/ning/billing/recurly/model/TestAccount.java
- src/test/java/com/ning/billing/recurly/model/TestBusinessEntities.java
- src/test/java/com/ning/billing/recurly/model/TestBusinessEntity.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
Support for multiple business entities:
- Add override_business_entity to Account.
- Add business_entity to Invoice.
- Add following endpoints to the client:
- GET /v2/business_entities
- GET /v2/business_entities/:business_entity_uuid
- GET /v2/business_entities/:business_entity_uuid/invoices
> Support for multiple business entities

- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/main/java/com/ning/billing/recurly/model/Transaction.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
- src/test/java/com/ning/billing/recurly/model/TestTransaction.java
This PR adds the action_result field to the Transaction and Subscription models. This field is needed for transactions that need an extra action to confirm the payment (Boleto, iDEAL and Sofort)
> [V2] Add action_result to Subscription and Transaction

- src/main/java/com/ning/billing/recurly/model/Invoice.java
- src/main/java/com/ning/billing/recurly/model/Purchase.java
- src/main/java/com/ning/billing/recurly/model/Subscription.java
- src/main/java/com/ning/billing/recurly/model/SubscriptionUpdate.java
- src/test/java/com/ning/billing/recurly/model/TestInvoice.java
- src/test/java/com/ning/billing/recurly/model/TestInvoiceCollection.java
- src/test/java/com/ning/billing/recurly/model/TestPurchase.java
- src/test/java/com/ning/billing/recurly/model/TestPurchaseWithRevRec.java
- src/test/java/com/ning/billing/recurly/model/TestSubscription.java
- src/test/java/com/ning/billing/recurly/model/TestSubscriptionUpdate.java
- src/test/java/com/ning/billing/recurly/model/push/TestNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestCloseInvoiceNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestNewInvoiceNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestPastDueInvoiceNotification.java
- src/test/java/com/ning/billing/recurly/model/push/invoice/TestProcessingInvoiceNotification.java
This PR adds `netTermsType` to the Invoice, Subscription, SubscriptionUpdate, and Purchase classes and their tests.
> Adds netTermsType to the Invoice, Subscription, SubscriptionUpdate, and Purchase classes and their tests

- src/main/java/com/ning/billing/recurly/model/Adjustment.java
- src/main/java/com/ning/billing/recurly/model/BusinessEntity.java
- src/test/java/com/ning/billing/recurly/model/TestAdjustements.java
- src/test/java/com/ning/billing/recurly/model/TestAdjustment.java
- src/test/java/com/ning/billing/recurly/model/TestBusinessEntities.java
- src/test/java/com/ning/billing/recurly/model/TestBusinessEntity.java
Changes on model BusinessEntity and Adjustment to get those params.
Add tests for origin_tax_address_source and destination_tax_address_source.
> Add origin_tax_address_source & destination_tax_address_source to business_entity and adjustment resource.

- src/main/java/com/ning/billing/recurly/model/AdjustmentRefund.java
- src/main/java/com/ning/billing/recurly/model/InvoiceRefund.java
- src/test/java/com/ning/billing/recurly/TestRecurlyClient.java
Adds percentage to refund amount, also adds percentage and amount_in_cents to individual adjustments.
> Refund changes

- src/main/java/com/ning/billing/recurly/RecurlyClient.java
- src/main/java/com/ning/billing/recurly/model/ExternalSubscription.java
- src/test/java/com/ning/billing/recurly/model/TestExternalSubscription.java
- src/test/java/com/ning/billing/recurly/model/TestExternalSubscriptions.java
fetch an external subscription by the uuid
> Get external sub by uuid
